name: Go CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-build-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24.5"

      - name: Run tests
        run: go test ./...

      - name: Build binaries
        run: |
          mkdir -p bin
          go build -o bin/node ./cmd/node
          go build -o bin/client ./cmd/client

      - name: Upload binary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: p2p-file-system-linux
          path: |
            bin/node
            bin/client